Repository keymanapp/keymanweb.com, pull requests merged in 2021-03, with the labels that each got.

#20 chore: automatically use web's beta during beta cycles
  inc/head.php
  inc/servervars.php
Labels: chore, feat

#22 chore: applies final suggestion from #20's review
  inc/head.php
Labels: chore

#23 feat: add a banner for pre-release announcement
  cdn/dev/css/kmw-desktop.css
  cdn/dev/css/kmw-mobile.css
  cdn/dev/css/kmw-tablet.css
  inc/head.php
  inc/servervars.php
  index.php
Labels: feat

#25 fix: replaces 'let' with 'var'
  inc/head.php
Labels: bug

#28 fix: delays kmw-dependent code 'til full page load
  cdn/dev/js/kmwlive.js
Labels: bug

#31 fix: removes use of undefined handler
  prog/languageexample.php
Labels: fix
