Repository keymanapp/keymanweb.com, pull requests merged in 2024-02, with the labels that each got.

#100 cherrypick: Update production to use shared-sites v0.4 :cherries:
  build.sh
Labels: production

#99 Update staging to use shared-sites v0.4
  build.sh
Labels: staging

#103 chore: Add liveliness check
  _control/alive.txt
Labels: staging, chore

#105 chore: Rename alive.txt to alive
  _control/alive
Labels: staging

#104 fix: use relative URL for language example lookup
  cdn/dev/js/kmwlive.js
  inc/head.php
Labels: fix

#102 chore: b17s1 merge staging into master
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  .htaccess
  App_Data/jobs/triggered/cache_keyboards/run.php
  App_Data/jobs/triggered/cache_keyboards/settings.job
  Dockerfile
  README.md
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _control/alive
  _control/info.php
  _control/ready.php
  _includes/2020/.keep
  _includes/autoload.php
  build.sh
  cdn/cdnrefresh.php
  cdn/dev/js/kmwlive.js
  cdn/dev/keys/keyrenderer.js
  composer.json
  composer.lock
  inc/head.php
  inc/servervars.php
  phpunit.xml
  prog/languageexample.php
  prog/renderLanguageExample.php
  resources/builder.inc.sh
  resources/cache-keyboards-cron
  resources/cache_keyboards.php
  resources/init-container.sh
  resources/keyman-site.conf
  resources/run.sh
  tests/InfrastructureTest.php
  web.config
Labels: chore

#108 chore: Add info to .htaccess
  .htaccess
  _control/info.php
Labels: chore, production

#109 chore: Merge master to staging for Sprint B17S1
  .htaccess
  _control/info.php
Labels: staging
