Repository keymanapp/keymanweb.com, pull requests merged in 2025-02, with the labels that each got.

#127 chore: Merge master to staging branch for beginning of Sprint B18S1
  .github/workflows/add-to-keyman-project.yml
  .github/workflows/ci.yml
  .gitignore
  .htaccess
  build.sh
  cdn/dev/css/kmw-desktop.css
  cdn/dev/js/kmwlive.js
  cdn/dev/js/sentry.bundle.5.28.0.min.js
  cdn/dev/keys/keys.css
  inc/head.php
  inc/servervars.php
  index.php
  prog/languageexample.php
  prog/renderLanguageExample.php
  resources/init-container.sh
Labels: staging

#129 refactor: clean up KeymanHosts usage and make consistent
  build.sh
  inc/servervars.php
  prog/renderLanguageExample.php
Labels: refactor

#133 chore: update sentry version, cleanup, and collect resource errors
  build.sh
  cdn/dev/js/sentry.js
  inc/head.php
Labels: chore

#136 fix: properly handle paths in init-container.sh
  resources/init-container.sh
Labels: fix

#137 refactor: stop use of $TestServer variable and friends
  inc/head.php
  inc/servervars.php
  inc/util.php
Labels: refactor
